sudo: required
services:
    - docker
before_install:
    - docker build -t akashinnf/reactive-fibonacci -f ./client/Dockerfile.dev ./client
script:
    - docker run akashinnf/reactive-fibonacci npm test -- --coverage
after_success:
    - docker build -t akashinnf/reactive-fibonacci-client ./client
    - docker build -t akashinnf/reactive-fibonacci-nginx ./nginx
    - docker build -t akashinnf/reactive-fibonacci-server ./server
    - docker build -t akashinnf/reactive-fibonacci-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push akashinnf/reactive-fibonacci-client
    - docker push akashinnf/reactive-fibonacci-nginx
    - docker push akashinnf/reactive-fibonacci-server
    - docker push akashinnf/reactive-fibonacci-worker