sudo: required
services:
    - docker
before_install:
    - docker build -t ca5h/reactive-fibonacci -f ./client/Dockerfile.dev
script:
    - docker run ca5h/reactive-fibonacci npm test -- --coverage
after_success:
    - docker build -t ca5h/reactive-fibonacci-client ./client
    - docker build -t ca5h/reactive-fibonacci-nginx ./nginx
    - docker build -t ca5h/reactive-fibonacci-server ./server
    - docker build -t ca5h/reactive-fibonacci-worker ./worker